name: "Install Python Dependencies"
description: "Install Python dependencies from requirements files"
inputs:
  working-directory:
    description: "The directory where your requirements files are located"
    required: true
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements-dev.txt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
